# base image
FROM node:20-alpine

WORKDIR /app

# install dependencies
COPY package*.json ./
RUN npm install

# add content
COPY . . 

# port
EXPOSE 5173

# start server
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]