"""add nullable for token count

Revision ID: 08b6bc5a7834
Revises: 60ef2b64687b
Create Date: 2025-12-11 14:54:38.057286

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08b6bc5a7834'
down_revision: Union[str, None] = '60ef2b64687b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chunks', 'token_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chunks', 'token_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
