"""optimize user table

Revision ID: 1b06718bed57
Revises: 7a3e6d4e2c26
Create Date: 2025-10-19 18:24:00.836534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b06718bed57'
down_revision: Union[str, None] = '7a3e6d4e2c26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_verified', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('interests', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('users', sa.Column('notification_enabled', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('preferred_sources', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('users', sa.Column('last_login', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_login')
    op.drop_column('users', 'preferred_sources')
    op.drop_column('users', 'notification_enabled')
    op.drop_column('users', 'interests')
    op.drop_column('users', 'is_verified')
    # ### end Alembic commands ###
