"""add defaults

Revision ID: 60ef2b64687b
Revises: 8e15ee4418f7
Create Date: 2025-12-11 12:25:04.368653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '60ef2b64687b'
down_revision: Union[str, None] = '8e15ee4418f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('status', sa.String(), nullable=False))
    op.alter_column('documents', 'storage_path',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('documents', 'indexed_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.create_unique_constraint(None, 'documents', ['content_hash'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'documents', type_='unique')
    op.alter_column('documents', 'indexed_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('documents', 'storage_path',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('documents', 'status')
    # ### end Alembic commands ###
