"""add user id to chunks table

Revision ID: 8e15ee4418f7
Revises: 8065fa3e4506
Create Date: 2025-12-08 17:44:52.451281

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e15ee4418f7'
down_revision: Union[str, None] = '8065fa3e4506'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chunks', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_chunks_user_id'), 'chunks', ['user_id'], unique=False)
    op.create_foreign_key(None, 'chunks', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chunks', type_='foreignkey')
    op.drop_index(op.f('ix_chunks_user_id'), table_name='chunks')
    op.drop_column('chunks', 'user_id')
    # ### end Alembic commands ###
